$schema: https://taskfile.dev/schema.json

version: '3'

vars:
  OTP_JAR: otp-shaded-2.9.0.jar

tasks:
  setup:
    desc: "Set up the project dependencies"
    cmds:
      - curl -L -o {{.OTP_JAR}} https://github.com/opentripplanner/OpenTripPlanner/releases/download/v2.9.0/otp-shaded-2.9.0.jar
      - curl -sLo galicia-latest.osm.pbf https://download.geofabrik.de/europe/spain/galicia-latest.osm.pbf
      - uv --directory build_xunta run ./gen_parroquias.py --pbf ../galicia-latest.osm.pbf

  download-xunta:
    desc: "Download Xunta de Galicia GTFS data (NAP MITRAMS)"
    cmds:
      - uv --directory build_xunta run ./build_static_feed.py {{.NAP_API_KEY}}
      - cp build_xunta/gtfs_xunta.zip feeds/xunta.zip

  download-renfe:
    desc: "Download Renfe GTFS data (NAP MITRAMS)"
    cmds:
      - uv --directory build_renfe run ./build_static_feed.py {{.NAP_API_KEY}} --merge
      - cp build_renfe/gtfs_renfe_galicia_merged.zip feeds/renfe.zip

  download-tranvias:
    desc: "Download A Coruña city GTFS data (NAP MITRAMS)"
    cmds:
      - uv --directory build_tranvias run ./build_static_feed.py {{.NAP_API_KEY}}
      - cp build_tranvias/gtfs_coruna.zip feeds/tranvias.zip

  download-vitrasa:
    desc: "Download Vitrasa GTFS data (Vigo Open Data)"
    cmds:
      - uv --directory build_vitrasa run ./build_static_feed.py
      - cp build_vitrasa/gtfs_vigo.zip feeds/vitrasa.zip

  download-feeds:
    desc: "Download all required data files"
    deps:
      - download-xunta
      - download-renfe
      - download-tranvias
      - download-vitrasa

  build-osm:
    desc: "Build OSM data for OpenTripPlanner"
    sources:
      - galicia-latest.osm.pbf
    cmds:
      - java -Xmx4G -jar {{.OTP_JAR}} --buildStreet .

  build-transit:
    desc: "Build transit data for OpenTripPlanner"
    cmds:
      - java -Xmx4G -jar {{.OTP_JAR}} --loadStreet --save .

  build:
    desc: "Build OpenTripPlanner and save the graph for future runs"
    cmds:
      - task: build-osm
      - task: build-transit

  run:
    desc: "Run the OpenTripPlanner server using the saved graph from the build task"
    cmds:
      - java -Xmx4G -jar {{.OTP_JAR}} --load . --serve

  proxy-renfe-rt:
    desc: "Run the Renfe releases proxy server"
    cmds:
      - uv --directory proxy_rt_renfe run ./main.py

  aio:
    desc: "Build and run OpenTripPlanner without saving the graph"
    cmds:
      - java -Xmx4G -jar {{.OTP_JAR}} --build . --serve
